export const FETCHED_EVERY_BEER = 'FETCHED_EVERY_BEER';
export const FETCHING_BEERS = 'FETCHING_BEERS';
export const FETCHED_BEERS = 'FETCHED_BEERS';
export const CHANGE_ONLY_LIKED_FILTER = 'CHANGE_ONLY_LIKED_FILTER';
export const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE';